# See: .github/workflows/labeler.yml and https://github.com/marketplace/actions/labeler
documentation:
- changed-files:
  - any-glob-to-any-file: 'docs/*'

maintenance:
- changed-files:
  - any-glob-to-any-file: ['.circleci/*', '.github/**/*']
