name: Docs Build Trigger

on:
  issue_comment:
    types: [created]
  pull_request:
    paths:
      - '.github/workflows/circle_trigger.yml'
  workflow_dispatch:
    inputs:
      make_target:
        description: "Enter make target: html html-noplot docs slimfast slimgallery"
        type: string

jobs:
  trigger-docs-builds:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && 
        github.event.issue.pull_request != '' && 
        contains(github.event.comment.body, '@napari-bot make')) ||
      github.event_name == 'workflow_dispatch'
    steps:
      - name: Determine make target
        id: determine-target
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          MAKE_TARGET_INPUT: ${{ github.event.inputs.make_target }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ -z "$MAKE_TARGET_INPUT" ]; then
              echo "::error::No make target provided in workflow dispatch input."
              exit 1
            fi
            echo "Using manual input target: $MAKE_TARGET_INPUT"
            echo "target=$MAKE_TARGET_INPUT" >> "$GITHUB_OUTPUT"
          else
            # Safely handle comment body through environment variable
            TARGET=$(echo "$COMMENT_BODY" | grep -oP '(?<=make\s)\w+' || echo "slimfast")
            ALLOWED_TARGETS="html html-noplot docs slimfast slimgallery"
            if ! grep -qw "$TARGET" <<< "$ALLOWED_TARGETS"; then
              echo "::error::Invalid target '$TARGET'. Allowed targets: $ALLOWED_TARGETS"
              exit 1
            fi
            echo "Using comment target: $TARGET"
            echo "target=$TARGET" >> "$GITHUB_OUTPUT"
          fi

      - name: Trigger CircleCI Pipeline
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          MAKE_TARGET: ${{ steps.determine-target.outputs.target }}
        run: |
          # Validate branch name isn't empty
          if [ -z "$BRANCH_NAME" ]; then
            echo "::error::Branch name is empty"
            exit 1
          fi
    
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}" \
            -d '{
              "branch": "'"$BRANCH_NAME"'",
              "parameters": {
                "make_target": "'"$MAKE_TARGET"'"
              }
            }' \
            "https://circleci.com/api/v2/project/gh/psobolewskiPhD/napari-docs/pipeline"

      - name: Trigger artifact build
        uses: ./.github/workflows/build_and_deploy.yml@main
        with:
          target_directory: dev
          make_target: ${{ steps.determine-target.outputs.target }}
        secrets: inherit