name: Remove html In PR description
on:
  # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
permissions:
  pull-requests: write

jobs:
  remove_comment:
    name: Remove html comments.
    uses: napari/napari/.github/workflows/edit_pr_description.yml@9c06e25a745586e84021a1bc86b1a315ded6205f # v0.9.1
