name: Remove "ready to merge" label

on:
  pull_request_target:
    types: [closed]
  workflow_call:


permissions:
  pull-requests: write

jobs:
  remove_label:
    name: Remove ready to merge label
    uses: napari/napari/.github/workflows/remove_ready_to_merge.yml@2f7f0572fd371fb5241d00a78ba7a26754d56058 # v0.6.3
