name: Remove "ready to merge" label

on:
  pull_request_target:
    types: [closed]
  workflow_call:


permissions:
  pull-requests: write

jobs:
  remove_label:
    name: Remove ready to merge label
    uses: napari/napari/.github/workflows/remove_ready_to_merge.yml@48fcd2f4351845419303b1d3a102dcb5ce6923ab # v0.7.0
